[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#ecu_diagnostics="0.90.60"
ecu_diagnostics = { git = "https://github.com/rnd-ash/ecu_diagnostics", branch="diag_server_unified" }
serial-rs = {git="https://github.com/rnd-ash/serial-rs"}
packed_struct="0.10.0"
static_assertions = "1.1.0"